spring.application.name=freshflow

spring.datasource.url=jdbc:postgresql://localhost:5432/freshflow
spring.datasource.username=freshflow_user
spring.datasource.password=freshflow_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true

spring.data.redis.host=localhost
spring.data.redis.port=6379