spring.application.name=freshflow

spring.datasource.url=jdbc:postgresql://localhost:5432/freshflow
spring.datasource.username=freshflow_user
spring.datasource.password=freshflow_pass
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.security=TRACE
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
razorpay.key.id=rzp_test_TCE0kd4i6gxAdP
razorpay.key.secret=jnrVG3cGgXJ2HD7g1kEwQjAQ
gemini.api.key=AQ.Ab8RN6LHny4M5k6KRoKdaAzJnU0uuJ1hbepvF5fVAtheSGdNlQ
